[package]
name = "gdk-common"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "William Casarin <jb55@jb55.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
chrono = "0.4"
lazy_static = "1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
libc = "0.2"
backtrace = "0.3"
hex = "0.4.0"
rand = "0.7.3"

[dependencies.bitcoin]
version = "0.23"
features = ["use-serde"]

[dependencies.elements]
version = "0.12"
features = ["serde"]
